version: "3.8"

services:
  nginx:
    # Use the latest version of the Nginx image
    image: nginx:latest
    # Map port 80 on the host to port 80 on the container
    ports:
      - "80:80"
    # Mount the local 'html' directory to the container's '/usr/share/nginx/html' directory
    volumes:
      - "./html:/usr/share/nginx/html"
