model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: azure/my_azure_deployment
      api_base: os.environ/AZURE_API_BASE
      api_key: "os.environ/AZURE_API_KEY"
      api_version: "2024-12-01-preview" # [OPTIONAL] litellm uses the latest azure api_version by default